export const SET_COLUMNS = 'sourceData/SET_COLUMNS';
export const ADD_COLUMN_TO_VISIBLE_COLUMNS_NAMES = 'sourceData/ADD_COLUMN_TO_VISIBLE_COLUMNS_NAMES';
export const REMOVE_COLUMN_FROM_VISIBLE_COLUMNS_NAMES = 'sourceData/REMOVE_COLUMN_FROM_VISIBLE_COLUMNS_NAMES';

export const SET_ROWS = 'sourceData/SET_ROWS';

export const GET_JSON_DATA_REQUEST = 'sourceData/GET_JSON_DATA_REQUEST';
